Add new design requirements
ibm-apiconnect/getting-started-archive pull request #21
Opened 2017-01-11 22:16 UTC by siddhipai

@adamkirkwood PTAL

2017-01-11 22:16 UTC, slnode commented
Can one of the admins verify this patch?

2017-01-11 22:46 UTC, adamkirkwood commented
![screen shot 2017-01-11 at 2 45 13 pm](https://cloud.githubusercontent.com/assets/52746/21869463/9b2849bc-d80c-11e6-8859-a2847a3e3dc9.png)

We need to make sure the content doesn't go beyond a maximum width of 1296px

2017-01-11 22:47 UTC, adamkirkwood commented
![screen shot 2017-01-11 at 2 46 13 pm](https://cloud.githubusercontent.com/assets/52746/21869509/c7baf89e-d80c-11e6-9ca9-ff74d54d21f1.png)

The line crossing through all the bullet points should be 2px in width

2017-01-11 22:50 UTC, adamkirkwood requested changes
Visual changes have been added as comments to #21

2017-01-12 14:31 UTC, ritch approved these changes
Please address comments in a separate PR

2017-01-12 14:31 UTC, ritch commented on proto/loopback_tutorial.html
> +      <li id="contents"><span id="contents">Create a new project</span></li>
`id="contents"` can only be used once because its an `id`

please fix in another PR (we can merge this to get the current HTML updated for preview)

2017-01-12 14:31 UTC, ritch commented on proto/loopback_tutorial.html
> +      <p id="propose">Propose a change on the</p>&nbsp<a href="#">source</a>.
`&nbsp` is missing a `;`

should be `&nbsp;`

2017-01-12 14:32 UTC, merged